# Generated by Django 4.2.5 on 2023-11-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gremio',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Gremio', models.CharField(max_length=150)),
                ('RUC_Gremio', models.PositiveIntegerField()),
                ('DNI_Secretario_General', models.PositiveIntegerField()),
                ('Nombre_Secretario_General', models.CharField(max_length=150)),
                ('DNI_Dirigente', models.PositiveIntegerField()),
                ('Nombre_Dirigente', models.CharField(max_length=150)),
                ('DNI_Presidente', models.PositiveIntegerField()),
                ('Nombre_Presidente', models.CharField(max_length=150)),
                ('Foto_Gremio', models.CharField(max_length=200)),
            ],
        ),
    ]
