# Generated by Django 4.2.5 on 2023-11-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gremio',
            name='DNI_Dirigente',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='gremio',
            name='DNI_Presidente',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='gremio',
            name='DNI_Secretario_General',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='gremio',
            name='RUC_Gremio',
            field=models.CharField(max_length=11),
        ),
    ]
